# fly.toml app configuration file generated for product-description-generator on 2023-05-01T22:21:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "product-description-generator"
primary_region = "lax"

[env]
  PORT = "8081"
  HOST = "product-description-generator.fly.dev"
  SHOPIFY_API_KEY = "78b49696400ca4c98a0144e026f5c527"
  SCOPES = "write_products"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
